In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\jphin\appdata\local\programs\python\python312\lib\site-packages (2.0.30)
Requirement already satisfied: psycopg2-binary in c:\users\jphin\appdata\local\programs\python\python312\lib\site-packages (2.9.11)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\jphin\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\jphin\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.0.3)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import pandas as pd
from sqlalchemy import create_engine, text

In [21]:
# Create Database Connection for Postgres
dbName = 'Hinshaw_Mortgage'
userName = 'postgres'
password = 'password'
engine = create_engine(f"postgresql://{userName}:{password}@localhost/{dbName}")
conn = engine.connect()

In [22]:
engine.connect()

In [23]:
employees_df = pd.read_csv("employees_clean.csv")
loans_df = pd.read_csv("loans_clean.csv")
ext_df = pd.read_csv("Ext_clean.csv")

In [24]:
create_employee_table = """
CREATE TABLE IF NOT EXISTS employees_clean (
    employee_id            INT PRIMARY KEY,
    first_name             TEXT,
    last_name              TEXT,
    job_title              TEXT,
    region                 TEXT,
    branch_id              INT,
    branch_location        TEXT,
    hire_date              DATE,
    employment_status      TEXT,
    compensation_type      TEXT,
    salary                 NUMERIC,
    bps_compensation       NUMERIC,
    manager_id             INT,
    tenure_years           NUMERIC,
    is_bps_compensation    INT,
    compensation_category  TEXT,
    full_name              TEXT,
    branch_label           TEXT
);
"""

In [25]:
create_loan_table = """
CREATE TABLE IF NOT EXISTS loans_clean (
    loan_number            INT PRIMARY KEY,
    application_date       DATE,
    lock_date              DATE,
    funding_date           DATE,
    loan_amount            INT,
    property_state         TEXT,
    property_type          TEXT,
    occupancy_type         TEXT,
    loan_purpose           TEXT,
    channel                TEXT,
    product_type           TEXT,
    interest_rate          NUMERIC,
    fico                   INT,
    cltv                   INT,
    dti                    INT,
    lock_term_days         INT,
    loan_status            TEXT,
    loan_officer_id        INT,
    account_executive_id   INT,
    underwriter_id         INT,
    processor_id           INT,
    compensation_bps       INT,
    compensation_amount    NUMERIC,
    branch_id              INT,
    pull_through_flag      INT,
    extension_count        INT
);
"""

In [26]:
create_extension_table = """
CREATE TABLE IF NOT EXISTS extensions_clean (
    extension_id                 INT PRIMARY KEY,
    loan_number                  INT,
    extension_sequence           INT,
    extension_request_date       DATE,
    extension_days               INT,
    extension_fee_percent        NUMERIC,
    extension_fee_amount         NUMERIC,
    requested_by_role            TEXT,
    approved_by_employee_id      INT,
    reason_code                  TEXT,
    lock_expiration_date_before  DATE,
    lock_expiration_date_after   DATE,
    FOREIGN KEY (loan_number) REFERENCES loans_clean(loan_number)
);
"""

In [27]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text(create_employee_table))
    conn.execute(text(create_loan_table))
    conn.execute(text(create_extension_table))

In [28]:
employees_df.to_sql("employees", engine, if_exists="append", index=False)
loans_df.to_sql("loans", engine, if_exists="append", index=False)
ext_df.to_sql("extensions", engine, if_exists="append", index=False)

69

In [29]:
pd.read_sql("SELECT COUNT(*) FROM employees", engine)

   count
0     75

In [30]:
pd.read_sql("SELECT COUNT(*) FROM loans", engine)

   count
0  10000

In [31]:
pd.read_sql("SELECT COUNT(*) FROM extensions", engine)

   count
0   4069