In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

# Create Database Connection for Postgres
dbName = 'Hinshaw_Mortgage'
userName = 'postgres'
password = 'password'
engine = create_engine(f"postgresql://{userName}:{password}@localhost/{dbName}")
conn = engine.connect()

In [2]:
engine.connect()

In [3]:
pd.read_sql("SELECT * FROM loans LIMIT 5", engine)

,Loan Number,Application Date,Lock Date,Funding Date,Loan Amount,Property State,Property Type,Occupancy Type,Loan Purpose,Channel,...,Loan Age (Days),Days To Fund,App To Lock Days,Lock To Fund Days,FICO Bucket,CLTV Bucket,High DTI Flag,Total Time In Process,Loan Status Simplified,Loan Purpose Simplified
0,70000001,2023-01-27,2023-01-30,None,439737,Tx,Sfr,Primary,Purchase,Wholesale,...,1175,NaN,3,NaN,Excellent (740-799),91-100%,0,3.0,Withdrawn,Purchase
1,70000002,2023-03-26,2023-03-31,2023-05-15,621903,Ny,Sfr,Investment,Purchase,Retail,...,1117,50.0,5,45.0,Prime+ (700-739),81-90%,0,50.0,Funded,Purchase
2,70000003,2023-02-23,2023-02-28,None,580294,Ny,Condo,Primary,Purchase,Retail,...,1148,NaN,5,NaN,Prime (660-699),71-80%,0,5.0,Withdrawn,Purchase
3,70000004,2023-03-31,2023-04-04,2023-05-25,764044,Ca,Sfr,Investment,Purchase,Retail,...,1112,55.0,4,51.0,Excellent (740-799),71-80%,0,55.0,Funded,Purchase
4,70000005,2023-03-20,2023-03-25,None,411397,Va,Sfr,Investment,Purchase,Retail,...,1123,NaN,5,NaN,Excellent (740-799),71-80%,0,5.0,Withdrawn,Purchase

In [4]:
pd.read_sql("SELECT * FROM employees LIMIT 5", engine)

,Employee ID,First Name,Last Name,Job Title,Region,Branch ID,Branch Location,Hire Date,Employment Status,Compensation Type,Salary,BPS Compensation,Manager ID,Tenure (Years),Is BPS Compensation,Compensation Category,Full Name,Branch Label
0,100,Daniel,Carson,Loan Officer,Midwest,22,Chicago,2015-04-05,Active,bps,0.0,130.0,None,11.0,1,BPS,Daniel Carson,Chicago - 22
1,101,Daniel,Hernandez,Loan Officer,East,12,Charlotte,2021-07-02,Active,bps,0.0,80.0,None,4.8,1,BPS,Daniel Hernandez,Charlotte - 12
2,102,Sophia,Shaw,Loan Officer,West,18,Los Angeles,2020-10-01,Active,bps,0.0,120.0,None,5.5,1,BPS,Sophia Shaw,Los Angeles - 18
3,103,Rebecca,Hernandez,Loan Officer,South,30,Atlanta,2015-08-19,Active,bps,0.0,100.0,None,10.7,1,BPS,Rebecca Hernandez,Atlanta - 30
4,104,Emily,Turner,Loan Officer,South,30,Atlanta,2017-05-05,Active,bps,0.0,90.0,None,9.0,1,BPS,Emily Turner,Atlanta - 30

In [5]:
pd.read_sql("SELECT * FROM extensions LIMIT 5", engine)

,Extension ID,Loan Number,Extension Number,Date Extension Requested,Extension (Days),Extension Cost (%),Extension Cost ($),Extension Requestor,Approved By (ID),Extension Reason,Expiration Before Extension,Expiration After Extension,Total Extension Days,Total Extension Cost ($),Extension Count,Extension Bucket
0,90001,70000004,1,2023-05-02,15,0.00250,1910.11,Processor,126,Title Issues,2023-05-04,2023-05-19,20,2865.17,2,1–2 Extensions
1,90002,70000004,2,2023-05-15,5,0.00125,955.06,Loan Officer,125,Appraisal Delay,2023-05-19,2023-05-24,20,2865.17,2,1–2 Extensions
2,90003,70000007,1,2023-04-22,15,0.00250,1189.77,Broker,128,Title Issues,2023-04-27,2023-05-12,30,2379.54,2,1–2 Extensions
3,90004,70000007,2,2023-05-10,15,0.00250,1189.77,Broker,138,Title Issues,2023-05-12,2023-05-27,30,2379.54,2,1–2 Extensions
4,90005,70000009,1,2023-05-10,15,0.00250,1043.73,Loan Officer,128,Appraisal Delay,2023-05-15,2023-05-30,30,2087.46,2,1–2 Extensions

In [6]:
create_view = """
CREATE OR REPLACE VIEW loan_extension_model AS
SELECT
    l."Loan Number" AS loan_number,
    l."Loan Amount" AS loan_amount,
    l."Application Date" AS application_date,
    l."Lock Date" AS lock_date,
    l."Funding Date" AS funding_date,
    l."FICO" AS fico,
    l."DTI" AS dti,
    l."CLTV" AS cltv,
    l."Product Type" AS product_type,
    l."Loan Purpose" AS loan_purpose,
    l."Channel" AS channel,
    l."Property State" AS property_state,
    l."Occupancy Type" AS occupancy_type,
    l."Loan Status" AS loan_status,
    l."Pull Through Flag" AS pull_through_flag,

    lo."Full Name" AS loan_officer,
    lo."Branch Location" AS loan_officer_branch,

    ex."Extension Number" AS extension_number,
    ex."Extension (Days)" AS extension_days,
    ex."Extension Cost ($)" AS extension_fee_amount,
    ex."Date Extension Requested" AS extension_request_date,
    ex."Extension Reason" AS reason_code,
    ex."Total Extension Days" AS total_extension_days,
    ex."Total Extension Cost ($)" AS total_extension_cost,
    ex."Extension Count" AS extension_count,

    approver."Full Name" AS extension_approver

FROM loans l
LEFT JOIN employees lo
    ON l.loan_officer_id = lo."Employee ID"
LEFT JOIN extensions ex
    ON l."Loan Number" = ex."Loan Number"
LEFT JOIN employees approver
    ON ex."Approved By (ID)" = approver."Employee ID";
"""

In [7]:
with engine.connect() as conn:
    conn.execute(text(create_view))

In [8]:
pd.read_sql('SELECT * FROM loan_extension_model LIMIT 10', engine)

,loan_number,loan_amount,application_date,lock_date,funding_date,fico,dti,cltv,product_type,loan_purpose,...,loan_officer_branch,extension_number,extension_days,extension_fee_amount,extension_request_date,reason_code,total_extension_days,total_extension_cost,extension_count,extension_approver
0,70000001,439737,2023-01-27,2023-01-30,None,745,34,92,Conventional,Purchase,...,Dallas,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None
1,70000002,621903,2023-03-26,2023-03-31,2023-05-15,700,29,83,Va,Purchase,...,Dallas,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None
2,70000003,580294,2023-02-23,2023-02-28,None,697,20,72,Fha,Purchase,...,Atlanta,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None
3,70000004,764044,2023-03-31,2023-04-04,2023-05-25,744,34,77,Jumbo,Purchase,...,Dallas,2.0,5.0,955.06,2023-05-15,Appraisal Delay,20.0,2865.17,2.0,Daniel Jones
4,70000004,764044,2023-03-31,2023-04-04,2023-05-25,744,34,77,Jumbo,Purchase,...,Dallas,1.0,15.0,1910.11,2023-05-02,Title Issues,20.0,2865.17,2.0,Sophia Ramirez
5,70000005,411397,2023-03-20,2023-03-25,None,765,32,79,Va,Purchase,...,Dallas,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None
6,70000006,389766,2023-03-04,2023-03-09,2023-04-17,757,31,82,Va,Purchase,...,Los Angeles,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None
7,70000007,475907,2023-02-23,2023-02-26,2023-04-20,705,27,83,Fha,Refi Rt,...,Chicago,2.0,15.0,1189.77,2023-05-10,Title Issues,30.0,2379.54,2.0,Michael Johnson
8,70000007,475907,2023-02-23,2023-02-26,2023-04-20,705,27,83,Fha,Refi Rt,...,Chicago,1.0,15.0,1189.77,2023-04-22,Title Issues,30.0,2379.54,2.0,Ethan Shaw
9,70000008,367275,2023-02-08,2023-02-11,2023-03-27,641,37,69,Fha,Refi Rt,...,Los Angeles,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None

In [13]:
pd.read_sql("SELECT COUNT(*) FROM loan_extension_model;", engine)

   count
0  11465